### ISSUE TITLE
Links broken on CDI-Sterotypes

### ISSUE THREAD

**Issue by Dantheman720** [jboss-developer/jboss-eap-quickstarts#1671]
https://github.com/jboss-developer/jboss-eap-quickstarts/tree/6.4.0.GA/cdi-stereotype

Both of the CDI-interceptor links are broken.  This is the most current GA tag and is producing errors on developer.redhat.com as well as jboss.org.

The broken link is https://github.com/jboss-developer/jboss-eap-quickstarts/blob/6.4.0.GA/cdi_interceptors/README.md

**Comment by sgilda** [comment]
@Dantheman720 : 

The quickstart README uses a relative link to the other quickstart, i.e.: `../cdi-interceptors/README.md`. 

The cdi-stereotype quickstart links is has 'tree' in the link.
I'm not clear why the relative link resolves to 'blob' in the link instead of 'tree'.

I don't think this is a quickstart issue.

**Comment by Dantheman720** [comment]
I think it's actually the link in the README.  It's because the relative link goes to ../cdi_interceptors/README.md instead of ../cdi-interceptors/README.md.  It looks like it was fixed in recent READMEs.  We are currently using tag 6.4.0.GA on RHD and jboss.org.  I can shoot a quick PR with the fix if that's ok.

**Comment by sgilda** [comment]
Ah, right! Let me see what I can do.

**Comment by sgilda** [comment]
It looks like that change was made by Jason in this commit: https://github.com/jboss-developer/jboss-eap-quickstarts/commit/8d9b0b373f688a1d04ad50fea78e349721f4da62

I need to investigate why the text shows `cdi-` but the link contains `cdi_`

**Comment by sgilda** [comment]
@Dantheman720 : 

We definitely fixed this here: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/6.4.x/cdi-stereotype/README.md

Do you know where you are getting the quickstart from?

**Comment by Dantheman720** [comment]
We are pulling the 6.4.0.GA tagged quickstarts from jboss-eap-quickstarts.  Would it be best to pull the 6.4.x?

**Comment by sgilda** [comment]
We didn't retag the release. Let me do some investigation and get back to you.

**Comment by sgilda** [comment]
@Dantheman720 : It sounds like you need to go against  6.4.x.  

Can I close this issue?

**Comment by Dantheman720** [comment]
Yeah, that sounds good.  I will change the tag we use on RHD and jboss.org.

Thanks Sande!
