### ISSUE TITLE
Some webapp projects are using broken Bootstrap CSS links

### ISSUE THREAD

**Issue by rafaeltuelho** [jboss-developer/jboss-eap-quickstarts#1722]
Some webapp projects are referencing broken Bootstrap CSS links.

For example you can observe this on [payment-cdi-event JSF Facelets template file](https://github.com/jboss-developer/jboss-eap-quickstarts/blob/540e8b210e7687368dcda592b968e394181b4eba/payment-cdi-event/src/main/webapp/WEB-INF/templates/template.xhtml#L27)

This older version (1.4.0) of bootstrap library can be found at: https://bootstrapdocs.com/v1.4.0/bootstrap.min.css

Would be nice to upgrade the bootstrap version used by JBoss quickstarts or use some kind of JS/CSS package manager tool (eg: [Bower](http://bower.io/)). This would be a good idea specially for modern web apps that use many JS/CSS frameworks....

**Comment by rafabene** [comment]
Hi Tuelhinho. 

I'll close this Github issue as I opened a ticket at https://issues.jboss.org/browse/JDF-855

Thanks

**Comment by rafaeltuelho** [comment]
:+1: :wink:

**Comment by sgilda** [comment]
@rafaeltuelho : I had to move the ticket here: https://issues.jboss.org/browse/JBEAP-2598
I've create a pull for the fix.

Thanks for reporting this issue!
