### ISSUE TITLE
kitchensink example wont compile unless I change my settings.xml

### ISSUE THREAD

**Issue by adietish** [jboss-developer/jboss-eap-quickstarts#2062]
If I create a kitchensink application in OpenShift, using  the eap templates that are shipped with our CDK, and clone the source Iocally, I end up having source that wont compile:
```
[ERROR] Non-resolvable import POM: Failure to find org.jboss.spec:jboss-javaee-6.0:pom:3.0.2.Final-redhat-15 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 80, column 25
[ERROR] Non-resolvable import POM: Failure to find org.jboss.as:jboss-as-ejb-client-bom:pom:7.5.0.Final-redhat-21 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 87, column 25
[ERROR] Non-resolvable import POM: Failure to find org.jboss.bom.eap:jboss-javaee-6.0-with-tools:pom:6.4.0.GA in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 67, column 25
[ERROR] Non-resolvable import POM: Failure to find org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:pom:6.4.0.GA in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ line 74, column 25
```
The eap templates, that are shipped with the CDK are using the 6.4.x branch, but this wont change if I use newer branches afaics.
I can only fix this by chaning my settings.xml, adding http://repository.jboss.org to my repositories. A manipulation that I find non-intuitive for non-seasoned developers that would want to checkout OpenShift/CDK.
We could easily solve this by adding the repo to the pom's in the examples or have the examples reference the root pom that has this repo defined.

**Comment by adietish** [comment]
I'm mistaken by thinking that adding the repositories to the root pom would help. The kitchensink example (for instance) wont use the root pom as parent, the suggested change thus wont help. 
I dont see any other solution than to change my local settings.xml which I this is far from being ideal. Thoughts?

**Comment by sgilda** [comment]
@adietish : The general instructions for deploying a JBoss EAP 6.4 quickstart to OpenShift are located here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/DEPLOY_TO_OPENSHIFT.md

Are you following those instructions? 

Also, some of the other quickstarts have specific instructions to deploy to OpensShift, for example, helloword-rs, helloworld-mdb, helloworld-ws, jax-rs-client, and wsat-simple. Have you tried any of them?

**Comment by adietish** [comment]
@sgilda thanks for chiming in. The instructions that you're pointing me to are instrutions for OpenShift v2. Sorry if I didnt mention this, but our CDK is OpenShift v3 based.

**Comment by sgilda** [comment]
@adietish : Yes, I understand. Unfortunately we no longer maintain the JBoss EAP 6.4 version of the quickstarts, which provided unstructions for deployment OpenShift v2. We do, however, plan to add instructions to the JBoss EAP 7.1 quickstarts to deploy to OpenShift v3. You can follow the progress on this JIRA: https://issues.jboss.org/browse/JBEAP-626

**Comment by adietish** [comment]
@sgilda I believe that this is not a matter of instructions. As a matter of fact the OpenShift templates are referring to the 6.4.x branch. But the very same problem seems to exist in the newer 7.1.x branch. So this imho isnt a matter of being properly supported or not. 
A simple change would allow people to checkout the example(s) from template in our Eclipse tooling without having to change their local config, which is required now.

**Comment by sgilda** [comment]
@adietish : I am as anxious to get the quickstarts working with OpenShift v3 as you are. 

As I said, we can no longer make changes to the JBoss EAP 6.4 quickstarts, but if you are more than welcome create a pull that allows the JBoss EAP 7.1 quickstarts to work on OpenShift v3. 

Just so you know, https://github.com/josefkarasek did some work to get the quickstarts to work on OpenShift v3. I have saved his work in my own Git branch here: https://github.com/sgilda/jboss-eap-quickstarts/tree/WIP-JBEAP-626. Based on his changes, I also started work on the instructions here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/DEPLOY_TO_OPENSHIFT_JBOSS_EAP7.md

Also, please run your suggestions by @ctomc to make sure your approach matches with his plans for running the quickstarts on OpenShift v3.

Please feel free to ping me with any other questions or suggestions. :-)

**Comment by adietish** [comment]
@sgilda thanks for the pointers. I'll try to get grasp the changes that josef did. Beside the changes for OpenShift my current main concern is that the example(s) afaics wont work out of the box locally. One needs afaics the jboss maven repository in the settings.xml, something I'd love to fix for added simplicity for the dummy user.
@ctomc WDYT?

**Comment by adietish** [comment]
@ctomc further checking kitchensink in the  different branches and tags I found out the following:
There are 7.x tags that point to states that work out of the box as they contain the repository that holds the required artifact(s). 
The following 2 tags work out of the box. They contain the  maven repo that holds the required maven artifact(s) (https://maven.repository.redhat.com/) and point to versions that are available:
* 7.1.0.Final
* 7.0.0.GA

While 7.0.0.Final points to a state where's nothing but a target folder in the repo.

So generally speaking, if the OpenShift templates shall be updated, we should have it pointing to 7.0.0.GA?

**Comment by psakar** [comment]
@adietish By 7.1.0.Final you mean tag https://github.com/jboss-developer/jboss-eap-quickstarts/tree/7.1.0.Final ? I suppose that is related to upstream JBossAS version 7.1.0

**Comment by sgilda** [comment]
@adietish : All quickstart updates should be applied to the 7.1.x-develop branch. That is where we test all changes. When we are sure they work, those updates are then cherry-picked to the 7.1.x branch that will be used to build the 7.1 product quickstarts.

For more information about the process, see the following instructions: 

* https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONTRIBUTING.md#contribute-a-quickstart
* https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONTRIBUTING.md#administrative-tasks

Also, if you look at what Josef was doing for the OpenShift quickstarts, I think you'll see that he was abled to deploy to OpenShift just by by adding a profile. [1]

[1] https://github.com/sgilda/jboss-eap-quickstarts/blob/WIP-JBEAP-626/greeter/pom.xml#L204

**Comment by adietish** [comment]
@psakar yes, I mean git tags (as stated). 
@sgilda I did not target changes in this repo. As I tried to express above, your tagged version 7.0.0.GA and 7.1.0.Final both work out of the box. My question was about what version OUR OpenShift templates should use, since you seem to imply 6.4.0 cannot be changed anymore.

**Comment by sgilda** [comment]
@adietish : Correct. We are no longer modifying source for the 6.4 or the 7.0 quickstarts. You must target the 7.1 quickstarts.

**Comment by adietish** [comment]
@sgilda ok, thanks for the info then. If 6.4.x examples are deprecated we should stop using them. Since 7.0.0.GA and 7.1.0.Final work out of the box for me, I consider my initial report a non-issue.

**Comment by luck3y** [comment]
Since the old quickstarts aren't going to be updated, I'm suggesting we close this issue. I'll assign it to myself, but close it in a few weeks unless we have some additional feedback. (FWIW, I can verify the old artifacts aren't buildable with the default config, but the 6.4 quickstarts are also not currently maintained from what I can ascertain.)
