### ISSUE TITLE
please update version jboss bom

### ISSUE THREAD

**Issue by vagnernogueira** [jboss-developer/jboss-eap-quickstarts#2067]
<version.jboss.bom.eap>7.0.0-SNAPSHOT</version.jboss.bom.eap> 
version not found in repository
see:
https://maven.repository.redhat.com/ga/org/jboss/bom/jboss-eap-javaee7/

**Comment by psakar** [comment]
use tag https://github.com/jboss-developer/jboss-eap-quickstarts/tree/EAP_7.0.0.GA

**Comment by ctomc** [comment]
I've just pushed 7.1.alpha branch to the repository that is derived from EAP 7.1.Alpha release quickstarts.
