### ISSUE TITLE
Cannot find javaee7 on maven repo

### ISSUE THREAD

**Issue by renatoppuccini** [jboss-developer/jboss-eap-quickstarts#2070]
during deploy on openshift I could not deploy jboss eap 7 image, due the fact maven cannot find javaee7 dependency on repository.
https://repo1.maven.org/maven2/org/jboss/bom/jboss-eap-javaee7-with-tools/7.0.0.GA/jboss-eap-javaee7-with-tools-7.0.0.GA.pom

I can browse up to here:
https://repo1.maven.org/maven2/org/jboss/bom
but there is no jboss-eap-javaee7 folder

**Comment by ctomc** [comment]
They are part of Red Hat Maven repository https://maven.repository.redhat.com/ga/org/jboss/bom/jboss-eap-javaee7-with-tools/
And quickstarts do have this repo configured in pom.xml

What QS does break for you?

**Comment by renatoppuccini** [comment]
I am trying the helloworld one, using branch 7.0.0-Beta on OpenShift using an eap7 image.

During s2i build I get this:
1 tar.go:308] Adding to tar: /tmp/s2i-build097263895/upload/src/src/main/webapp/WEB-INF/beans.xml as src/src/main/webapp/WEB-INF/beans.xml
I0803 19:03:36.997054       1 tar.go:308] Adding to tar: /tmp/s2i-build097263895/upload/src/src/main/webapp/index.html as src/src/main/webapp/index.html
I0803 19:03:37.583757       1 docker.go:805] Waiting for container "s2i_registry_access_redhat_com_jboss_eap_7_eap70_openshift_sha256_2fcea3fcc642cee9e31184e83dbcd4402d6a02710a4ad882669c6db164e4df73_b14d553e" to stop ...
I0803 19:03:38.355082       1 sti.go:585] Found pom.xml... attempting to build with 'mvn -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package -Djava.net.preferIPv4Stack=true '
I0803 19:03:38.987511       1 sti.go:592] Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
I0803 19:03:40.829005       1 sti.go:585] Using Apache Maven 3.0.5 (Red Hat 3.0.5-17)
I0803 19:03:40.829067       1 sti.go:585] Maven home: /usr/share/maven
I0803 19:03:40.829084       1 sti.go:585] Java version: 1.8.0_131, vendor: Oracle Corporation
I0803 19:03:40.829100       1 sti.go:585] Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-3.b12.el7_3.x86_64/jre
I0803 19:03:40.829112       1 sti.go:585] Default locale: en_US, platform encoding: ANSI_X3.4-1968
I0803 19:03:40.829126       1 sti.go:585] OS name: "linux", version: "3.10.0-514.el7.x86_64", arch: "amd64", family: "unix"
I0803 19:03:40.858556       1 sti.go:592] Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/jboss -Duser.name=jboss
I0803 19:03:42.891152       1 sti.go:585] [INFO] Error stacktraces are turned on.
I0803 19:03:43.215586       1 sti.go:585] [INFO] Scanning for projects...
I0803 19:03:44.042991       1 sti.go:585] Downloading: https://repo1.maven.org/maven2/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:05:51.646553       1 sti.go:585] Downloading: https://maven.repository.redhat.com/ga/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:07:59.036659       1 sti.go:585] Downloading: https://maven.repository.redhat.com/earlyaccess/all/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:10:06.388682 1 sti.go:585] Downloading: https://maven.repository.redhat.com/techpreview/all/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:10:06.388682       1 sti.go:585] Downloading: https://maven.repository.redhat.com/techpreview/all/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:12:13.622466       1 sti.go:585] Downloading: http://jboss-developer.github.io/temp-maven-repo/org/jboss/spec/jboss-javaee-7.0/1.0.3.Final/jboss-javaee-7.0-1.0.3.Final.pom
I0803 19:14:20.891161       1 sti.go:585] [ERROR] The build could not read 1 project -> [Help 1]
I0803 19:14:20.892702       1 sti.go:585] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
I0803 19:14:20.892758       1 sti.go:585] [ERROR] Non-resolvable import POM: Could not transfer artifact org.jboss.spec:jboss-javaee-7.0:pom:1.0.3.Final from/to central (https://repo1.maven.org/maven2): Connection to https://repo1.maven.org refused @ line 123, column 25
I0803 19:14:20.892775       1 sti.go:585] [ERROR] 'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 136, column 21
I0803 19:14:20.892824       1 sti.go:585] [ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar is missing. @ line 144, column 21
I0803 19:14:20.892840 1 sti.go:585] [ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec:jar is missing. @ line 151, column 21

**Comment by ctomc** [comment]
Don't use 7.0.0-Beta branch use either 7.0.0.GA tag 
https://github.com/jboss-developer/jboss-eap-quickstarts/tree/7.0.0.GA
or at this point 7.1.0.Beta branch
https://github.com/jboss-developer/jboss-eap-quickstarts/tree/7.1.0.Beta/

both should work just fine.

the 7.0.0.Beta was using early access maven repository as EAP was not GA at the time. 
But now it already is :-)
