### ISSUE TITLE
wrong URL in docs - kitchensink-ear

### ISSUE THREAD

**Issue by jmazzitelli** [jboss-developer/jboss-eap-quickstarts#2075]
In the README for kitchensink-ear:

https://github.com/jboss-developer/jboss-eap-quickstarts/blob/7.1.0.Beta/kitchensink-ear/README.md

it says:

```
The application will be running at the following URL: http://localhost:8080/kitchensink-ear/.
```
That URL seems incorrect. It results in:

```
<html><head><title>Error</title></head><body>404 - Not Found</body></html>
```

EAP log message says this:

```
16:44:36,373 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 64) WFLYUT0021: Registered web context: '/kitchensink-ear-web' for server 'default-server'
```
Thus, when i tried this URL, it worked: http://localhost:8080/kitchensink-ear-web

**Comment by ctomc** [comment]
fixed in 7.1 branch / 7.1.0.GA release
