### ISSUE TITLE
No master branch

### ISSUE THREAD

**Issue by johnfosborneiii** [jboss-developer/jboss-eap-quickstarts#2076]
The removal of the master branch breaks all of the OpenShift template defaults for quickstarts. Can someone please re-add the master branch?

**Comment by ctomc** [comment]
this repository is read-only repo where only released versions of EAP quickstarts  (done on each EAP release) are published.
Development of quickstarts is done in upstream WildFly repository https://github.com/wildfly/quickstart
which does have master branch.
This repository will never have one anymore.

In any case it is safer for any repository / work that depends on EAP quickstarts to link to a branch or a tag and not master.
