### ISSUE TITLE
Consider splitting the code in ejb-security-interceptors into separate client/server packages.

### ISSUE THREAD

**Issue by yeroc** [jboss-developer/jboss-eap-quickstarts#737]
I think it would be easier to follow what's going on with this quickstart if the code were split according to where it runs (client-side or server-side).  Additionally it would be great if this were instead built on top of the ejb-remote quickstart as I believe this is the more common scenario, where a standalone remote client needs to access EJBs while switching the caller's identity.  

Thanks,
Corey

**Comment by ctomc** [comment]
ejb-security-interceptros is going away in 7.2, in 7.1 it is mostly replaced with two other quickstarts.
